# Configure an in-memory test database instance
spring.datasource.url=jdbc:h2:mem:capstonedb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Tell Hibernate to auto-generate tables matching your Java entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true